language: java
jdk:
  - openjdk8
install: gradle wrapper --gradle-version 4.4
before_install:
  - chmod +x gradlew

addons:
  postgresql: "9.6" // change "9.5" for your postgres specific version

before_script:
  - psql -c "create database aries;" -U postgres // your database name
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'postgres'" // if your password is different from 'postgres` use that one here

services:
  - postgresql